name: app_antibioticos
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mongo_dart: ^0.7.4
  flutter_widget_from_html_core: ^0.8.5+1
  flutter_secure_storage: ^4.2.1
  pull_to_refresh: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
      - assets/
  
