export 'package:app_antibioticos/models/player_model.dart';
export 'package:app_antibioticos/models/table_values.dart';
export 'package:app_antibioticos/models/firtsanswer_model.dart';
export 'package:app_antibioticos/models/firstquestion_model.dart';
export 'package:app_antibioticos/models/secondanswer_model.dart';
export 'package:app_antibioticos/models/secondquestion_model.dart';
export 'package:app_antibioticos/models/thirdanswer_model.dart';
export 'package:app_antibioticos/models/thirdquestion_model.dart';
export 'package:app_antibioticos/models/backpack_model.dart';
